name: Deploy HTML to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to IIS via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: 21
          protocol: ftp     # explicitly set to FTP
          local-dir: "./"   # or "public/" if your HTML files are inside a folder
          server-dir: "/"   # adjust if IIS expects /wwwroot/ or similar

      - name: Restart IIS
        run: |
          iisreset /restart
        shell: cmd
